### ISSUE TITLE
New token: REP

### ISSUE THREAD

**Issue by danimesq** [hilmarx/ipfswap#20]

**Comment by hilmarx** [comment]
The tokens you mentioned are already listed, you simply cannot search for them via acronym. 

<img width="1021" alt="Screenshot 2019-11-04 at 20 40 36" src="https://user-images.githubusercontent.com/19579480/68152188-7017a400-ff43-11e9-9e8a-253112e3b3b1.png">

**Comment by danimesq** [comment]
Reference: https://github.com/hilmarx/ipfswap/issues/13
