### ISSUE TITLE
New token: DGX

### ISSUE THREAD

**Issue by danimesq** [hilmarx/ipfswap#5]

**Comment by danimesq** [comment]
@hilmarx 
As there is already DAI and even WBTC, it would also need DGX. How it manages the list of tokens?

**Comment by hilmarx** [comment]
https://github.com/hilmarx/ipfswap/blob/829ed13d1136d5e66391d5754479f82f60d8ceb8/javascript/currencies.js#L143-L173

**Comment by danimesq** [comment]
It is already in Kyber list of tokens.
