### ISSUE TITLE
ipfswap.com doesn't works

### ISSUE THREAD

**Issue by danimesq** [hilmarx/ipfswap#9]
@hilmarx

**Comment by hilmarx** [comment]
I can connect the domain, but only if the IPFS hash doesn't change any more. The hash of the current repo is: QmXJSK7VaNoAmZr4Fp7Z5faqNSnxGpMs3ENfPhncnQ7ag2. If you want to add more updates, let's wait until they are done before I set the Pinate link to my hosting service.

**Comment by danimesq** [comment]
You could use IPNS to update the site while keeping the same hash.

**Comment by hilmarx** [comment]
I think I would still have to publish new IPFS hashes to my IPNS name every single time it gets updated, so it is better to do it after some iterations are complete.

**Comment by danimesq** [comment]
There is a IPFS daemon which automatically gets the hash of a folder when it detects modifications, and would update it to a IPNS name.

**Comment by hilmarx** [comment]
works again.
